module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  projects: [
    '<rootDir>/',
    '<rootDir>/shared',
    '<rootDir>/bootstrap',
    '<rootDir>/operator-agent',
    '<rootDir>/fallback',
  ],
  roots: ['<rootDir>/src', '<rootDir>/tests', '<rootDir>/__tests__'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    'core/**/*.ts',
    'memory/**/*.ts',
    'planner/**/*.ts',
    '!src/**/*.d.ts',
    '!src/main.ts',
    '!**/node_modules/**',
    '!**/*.test.ts',
    '!**/*.spec.ts',
  ],
  coverageDirectory: process.env.COVERAGE_DIR || 'coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json-summary'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  testTimeout: 30000,
  verbose: true,
};
