import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';

type ResultStatus = 'PASS' | 'FAIL' | 'ERROR' | 'UNRESOLVED';
type Severity = 'INFO' | 'MINOR' | 'MAJOR' | 'BLOCKER';
type Decision = 'ACCEPT_CANONICAL' | 'REJECT_NON_CANONICAL' | 'DEFER_PENDING_EVIDENCE' | 'REJECT_AUTHORITY_BYPASS' | 'REJECT_PROVENANCE_INCOMPLETE' | 'REJECT_REPLAY_FAILURE' | 'ACCEPT_GOVERNED_INVALIDATION' | 'ERROR_MALFORMED_INPUT';
type FailureCode = 'NONE' | 'AUTHORITY_BYPASS' | 'EVIDENCE_MISSING' | 'EVIDENCE_UNREGISTERED' | 'EVIDENCE_INVALIDATED' | 'EPISTEMIC_UNSUPPORTED' | 'PROVENANCE_INCOMPLETE' | 'REPLAY_DIVERGENCE' | 'EXTENSION_BYPASS' | 'MALFORMED_INPUT' | 'CONFLICT_UNRESOLVED';

const FAILURE_SEVERITY: Record<FailureCode, Severity> = { NONE:'INFO', AUTHORITY_BYPASS:'BLOCKER', EVIDENCE_MISSING:'BLOCKER', EVIDENCE_UNREGISTERED:'BLOCKER', EVIDENCE_INVALIDATED:'MAJOR', EPISTEMIC_UNSUPPORTED:'BLOCKER', PROVENANCE_INCOMPLETE:'BLOCKER', REPLAY_DIVERGENCE:'BLOCKER', EXTENSION_BYPASS:'BLOCKER', MALFORMED_INPUT:'MAJOR', CONFLICT_UNRESOLVED:'MAJOR' };
const INVARIANTS = ['INV-AUTH-01','INV-EVID-01','INV-EPIST-01','INV-CAUSAL-01','INV-PROV-01','INV-MOD-01','INV-GOV-01'] as const;

interface Evidence { id:string; content:string; status:'ADMISSIBLE'|'INVALIDATED'; provenance:string; }
interface Proposal { id:string; actor_type:'COGNITIVE'|'EXECUTION'|'AUTHORITY'; claim:string; confidence:number; evidence_ids:string[]; provider:string; runtime:string; requested_transition:string; human_approval?:{approved:boolean; approver_id?:string; provenance_complete:boolean}; }
interface Fixture { fixture_id:string; fixture_version:string; description:string; target_invariants:string[]; expected_decision:Decision; expected_failure_code:FailureCode; required_evidence_ids:string[]; policy_version:string; authority_context_id:string; provider_variants:string[]; bypass_attempts:string[]; expected_replay_match:boolean; evidence:Evidence[]; proposal:Proposal; mutation?:{kind:'INVALIDATE_EVIDENCE'|'MUTATE_PROPOSAL'|'MUTATE_POLICY'}; }
interface Manifest { manifest_version:string; canonicalization_profile:string; hash_algorithm:'sha256'; fixtures:Fixture[]; }
interface AuthorityContext { id:string; canonical_writer:'AUTHORITY_ENGINE'; }
interface DecisionRecord { decision:Decision; failure_code:FailureCode; transition:string|null; input_hash:string; }
interface ProvenanceReceipt { proposal_id:string; actor_type:Proposal['actor_type']; provider:string; runtime:string; evidence_ids:string[]; evidence_snapshot_hash:string; policy_version:string; authority_context_id:string; decision:Decision; decision_hash:string; canonical_transition_hash:string|null; }
interface ExecutionRecord { benchmark_id:string; harness_version:string; fixture_id:string; invariant_id:string; engine_version:string; input_hash:string; evidence_snapshot_hash:string; policy_snapshot_hash:string; authority_context_hash:string; decision:Decision; canonical_transition_hash:string|null; provenance_hash:string; replay_decision_hash:string|null; replay_match:boolean|null; bypass_attempt:string|null; bypass_result:string|null; status:ResultStatus; failure_code:FailureCode; severity:Severity; artifact_refs:string[]; }

const ROOT = path.resolve(__dirname, '../..');
const MANIFEST_PATH = path.join(ROOT, 'benchmarks/comp-m1-1/fixtures.json');
const OUTPUT_PATH = path.join(ROOT, 'verification/comp-m1-1/m1-1-execution.json');

function normalizeTimestamp(value:unknown):unknown { if (typeof value !== 'string') return value; const isoLike=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})$/; if(!isoLike.test(value)) return value; const date=new Date(value); return Number.isNaN(date.getTime())?value:date.toISOString(); }
function canonicalize(value:unknown):unknown { if(Array.isArray(value)) return value.map(canonicalize); if(value&&typeof value==='object'){const input=value as Record<string,unknown>; const out:Record<string,unknown>={}; for(const key of Object.keys(input).sort()) out[key]=canonicalize(input[key]); return out;} return normalizeTimestamp(value); }
function canonicalJson(value:unknown):string { return JSON.stringify(canonicalize(value)); }
function hashDomain(domain:string,value:unknown):string { return crypto.createHash('sha256').update(`CODESSA-COMP-M1-1:${domain}:v1\n${canonicalJson(value)}`,'utf8').digest('hex'); }
function validateFixture(f:Fixture):void { if(!/^COMP-M1-1-FX-\d{4}$/.test(f.fixture_id)) throw new Error(`invalid fixture_id: ${f.fixture_id}`); if(!/^v\d+\.\d+$/.test(f.fixture_version)) throw new Error(`invalid fixture_version: ${f.fixture_id}`); if(!f.policy_version||!f.authority_context_id) throw new Error(`missing policy/context: ${f.fixture_id}`); if(!f.provider_variants.length) throw new Error(`missing provider variants: ${f.fixture_id}`); if(!INVARIANTS.some(id=>f.target_invariants.includes(id))) throw new Error(`fixture has no invariant: ${f.fixture_id}`); }

class EvidenceRegistry { private readonly entries=new Map<string,Evidence>(); register(e:Evidence):void{this.entries.set(e.id,{...e});} snapshot(ids:string[]):Evidence[]{return ids.map(id=>this.entries.get(id)).filter((e):e is Evidence=>Boolean(e));} invalidate(id:string):void{const e=this.entries.get(id); if(!e) throw new Error(`cannot invalidate unknown evidence ${id}`); e.status='INVALIDATED';} }

class AuthorityEngine {
  readonly version='M1-1-AUTH-ENGINE-v0.1';
  evaluate(proposal:Proposal,evidence:Evidence[],requiredEvidenceIds:string[],context:AuthorityContext,policyVersion:string):DecisionRecord{
    if(context.canonical_writer!=='AUTHORITY_ENGINE') return this.record('REJECT_AUTHORITY_BYPASS','AUTHORITY_BYPASS',null,proposal,evidence,context,policyVersion);
    if(proposal.actor_type!=='AUTHORITY'&&proposal.requested_transition==='DIRECT_CANONICAL_WRITE') return this.record('REJECT_AUTHORITY_BYPASS','AUTHORITY_BYPASS',null,proposal,evidence,context,policyVersion);
    const evidenceById=new Map(evidence.map(e=>[e.id,e]));
    for(const id of requiredEvidenceIds){const e=evidenceById.get(id); if(!e) return this.record('REJECT_NON_CANONICAL','EVIDENCE_UNREGISTERED',null,proposal,evidence,context,policyVersion); if(e.status!=='ADMISSIBLE') return this.record('REJECT_NON_CANONICAL','EVIDENCE_INVALIDATED',null,proposal,evidence,context,policyVersion);}
    if(requiredEvidenceIds.length===0&&proposal.confidence>0) return this.record('REJECT_NON_CANONICAL','EPISTEMIC_UNSUPPORTED',null,proposal,evidence,context,policyVersion);
    if(proposal.human_approval?.approved&&!proposal.human_approval.provenance_complete) return this.record('REJECT_PROVENANCE_INCOMPLETE','PROVENANCE_INCOMPLETE',null,proposal,evidence,context,policyVersion);
    if(proposal.requested_transition==='CONFLICTING_TOOL_UPDATE') return this.record('DEFER_PENDING_EVIDENCE','CONFLICT_UNRESOLVED',null,proposal,evidence,context,policyVersion);
    if(proposal.requested_transition==='GOVERNED_INVALIDATION'&&evidence.some(e=>e.status==='INVALIDATED')) return this.record('ACCEPT_GOVERNED_INVALIDATION','NONE','GOVERNED_INVALIDATION',proposal,evidence,context,policyVersion);
    return this.record('ACCEPT_CANONICAL','NONE',proposal.requested_transition,proposal,evidence,context,policyVersion);
  }
  private record(decision:Decision,failure_code:FailureCode,transition:string|null,proposal:Proposal,evidence:Evidence[],context:AuthorityContext,policyVersion:string):DecisionRecord{
    const authorityProposal={...proposal,provider:'<PROVIDER_NEUTRAL>',runtime:'<RUNTIME_NEUTRAL>'};
    const input_hash=hashDomain('authority-input',{proposal:authorityProposal,evidence,authority_context:context,policy_version:policyVersion,engine_version:this.version});
    return {decision,failure_code,transition,input_hash};
  }
}

function provenanceReceipt(proposal:Proposal,evidence:Evidence[],decision:DecisionRecord,context:AuthorityContext,policyVersion:string,canonicalTransitionHash:string|null):ProvenanceReceipt { const evidence_snapshot_hash=hashDomain('evidence-snapshot',evidence); const decision_hash=hashDomain('decision',decision); return {proposal_id:proposal.id,actor_type:proposal.actor_type,provider:proposal.provider,runtime:proposal.runtime,evidence_ids:[...proposal.evidence_ids],evidence_snapshot_hash,policy_version:policyVersion,authority_context_id:context.id,decision:decision.decision,decision_hash,canonical_transition_hash:canonicalTransitionHash}; }

function runFixture(fixture:Fixture,engine:AuthorityEngine,provider:string):ExecutionRecord[]{ const registry=new EvidenceRegistry(); for(const e of fixture.evidence) registry.register(e); if(fixture.mutation?.kind==='INVALIDATE_EVIDENCE') registry.invalidate(fixture.required_evidence_ids[0]); const evidence=registry.snapshot(fixture.proposal.evidence_ids); const context:AuthorityContext={id:fixture.authority_context_id,canonical_writer:'AUTHORITY_ENGINE'}; const proposal={...fixture.proposal,provider}; const decision=engine.evaluate(proposal,evidence,fixture.required_evidence_ids,context,fixture.policy_version); const canonicalTransitionHash=decision.transition?hashDomain('canonical-transition',{transition:decision.transition,input_hash:decision.input_hash}):null; const receipt=provenanceReceipt(proposal,evidence,decision,context,fixture.policy_version,canonicalTransitionHash); const expectedPass=decision.decision===fixture.expected_decision&&decision.failure_code===fixture.expected_failure_code; const replayDecision=engine.evaluate(proposal,evidence,fixture.required_evidence_ids,context,fixture.policy_version); const replayDecisionHash=hashDomain('decision',replayDecision); const originalDecisionHash=hashDomain('decision',decision); const replayMatch=replayDecisionHash===originalDecisionHash; const bypassAttempt=fixture.bypass_attempts[0]??null; const bypassResult=bypassAttempt?(bypassAttempt==='direct_canonical_write'||bypassAttempt==='extension_authority_bypass'?'REJECTED':'NOT_APPLICABLE'):null; const status:ResultStatus=expectedPass&&(!fixture.expected_replay_match||replayMatch)?'PASS':'FAIL'; const severity=status==='PASS'?'INFO':FAILURE_SEVERITY[decision.failure_code]||'BLOCKER'; return fixture.target_invariants.map(invariant_id=>({benchmark_id:'CODESSA-COMP-M1-1',harness_version:'v0.1',fixture_id:fixture.fixture_id,invariant_id,engine_version:engine.version,input_hash:decision.input_hash,evidence_snapshot_hash:receipt.evidence_snapshot_hash,policy_snapshot_hash:hashDomain('policy',fixture.policy_version),authority_context_hash:hashDomain('authority-context',context),decision:decision.decision,canonical_transition_hash:canonicalTransitionHash,provenance_hash:hashDomain('provenance',receipt),replay_decision_hash:fixture.expected_replay_match?replayDecisionHash:null,replay_match:fixture.expected_replay_match?replayMatch:null,bypass_attempt:bypassAttempt,bypass_result:bypassResult,status,failure_code:status==='PASS'?'NONE':decision.failure_code,severity,artifact_refs:['verification/comp-m1-1/m1-1-execution.json']})); }
function selfTestMalformedManifest():boolean{try{validateFixture({} as Fixture); return false;}catch{return true;}}

function main():void{
  const manifest=JSON.parse(fs.readFileSync(MANIFEST_PATH,'utf8')) as Manifest; if(manifest.hash_algorithm!=='sha256') throw new Error('unsupported hash algorithm'); manifest.fixtures.forEach(validateFixture); const engine=new AuthorityEngine(); const records:ExecutionRecord[]=[]; for(const fixture of manifest.fixtures) for(const provider of fixture.provider_variants) records.push(...runFixture(fixture,engine,provider));
  const providerRecords=records.filter(r=>r.fixture_id==='COMP-M1-1-FX-0008'); const providerSubstitutionStable=providerRecords.length===2&&new Set(providerRecords.map(r=>r.input_hash)).size===1&&new Set(providerRecords.map(r=>r.decision)).size===1;
  const selfTests=[{id:'ST-001',fixture:'COMP-M1-1-FX-0001',name:'valid transition acceptance'},{id:'ST-002',fixture:'COMP-M1-1-FX-0002',name:'unsupported high-confidence rejection'},{id:'ST-003',fixture:'COMP-M1-1-FX-0003',name:'direct canonical write rejection'},{id:'ST-004',fixture:'COMP-M1-1-FX-0004',name:'evidence admission gating'},{id:'ST-005',fixture:'COMP-M1-1-FX-0005',name:'provenance completeness blocking'},{id:'ST-006',fixture:'COMP-M1-1-FX-0006',name:'deterministic replay'},{id:'ST-007',fixture:'COMP-M1-1-FX-0007',name:'mutation detection'},{id:'ST-008',fixture:'COMP-M1-1-FX-0008',name:'provider substitution',forcedStatus:providerSubstitutionStable?'PASS':'FAIL' as const},{id:'ST-009',fixture:'COMP-M1-1-FX-0009',name:'extension bypass'},{id:'ST-010',fixture:'COMP-M1-1-FX-0010',name:'malformed fixture handling'}];
  const byFixture=new Map<string,ExecutionRecord[]>(); for(const record of records){const arr=byFixture.get(record.fixture_id)??[]; arr.push(record); byFixture.set(record.fixture_id,arr);} const selfTestResults=selfTests.map(test=>{if(test.id==='ST-010') return {...test,status:selfTestMalformedManifest()?'PASS':'FAIL'}; const fixtureRecords=byFixture.get(test.fixture)??[]; const forced='forcedStatus' in test?test.forcedStatus:undefined; return {...test,status:forced??(fixtureRecords.length>0&&fixtureRecords.every(r=>r.status==='PASS')?'PASS':'FAIL')};});
  const acceptance={all_self_tests_pass:selfTestResults.every(t=>t.status==='PASS'),result_schema_valid:records.every(r=>Boolean(r.benchmark_id&&r.harness_version&&r.fixture_id&&r.invariant_id&&r.input_hash&&r.provenance_hash)),replay_hashes_match:records.filter(r=>r.replay_match!==null).every(r=>r.replay_match===true),mutation_expected_failures:records.filter(r=>['COMP-M1-1-FX-0007','COMP-M1-1-FX-0009'].includes(r.fixture_id)).every(r=>r.status==='PASS'),governed_error_handling:selfTestMalformedManifest()===true,stable_artifact_reference:true};
  const conformance=Object.values(acceptance).every(Boolean)?'CONFORMANT':(selfTestResults.some(t=>t.status==='FAIL')?'NON-CONFORMANT':'UNRESOLVED'); const implementationSha256=crypto.createHash('sha256').update(fs.readFileSync(__filename)).digest('hex'); const fixtureManifestSha256=crypto.createHash('sha256').update(fs.readFileSync(MANIFEST_PATH)).digest('hex');
  const output={benchmark_id:'CODESSA-COMP-M1-1',harness_version:'v0.1',execution_profile:manifest.canonicalization_profile,hash_algorithm:manifest.hash_algorithm,implementation_sha256:implementationSha256,fixture_manifest_sha256:fixtureManifestSha256,conformance,self_tests:selfTestResults,acceptance,records,record_count:records.length}; fs.mkdirSync(path.dirname(OUTPUT_PATH),{recursive:true}); const artifactContent=canonicalJson(output)+'\n'; fs.writeFileSync(OUTPUT_PATH,artifactContent,'utf8'); const artifactSha256=crypto.createHash('sha256').update(artifactContent,'utf8').digest('hex'); fs.writeFileSync(`${OUTPUT_PATH}.sha256`,`${artifactSha256}  m1-1-execution.json\n`,'utf8'); process.stdout.write(`CONFORMANCE=${conformance}\nSELF_TESTS=${selfTestResults.filter(t=>t.status==='PASS').length}/${selfTestResults.length}\nRECORDS=${records.length}\nOUTPUT=${OUTPUT_PATH}\nSHA256=${artifactSha256}\n`); if(conformance!=='CONFORMANT') process.exitCode=1;
}
main();
