import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
type Decision='ACCEPT_CANONICAL'|'REJECT_NON_CANONICAL'|'DEFER_PENDING_EVIDENCE'|'REJECT_AUTHORITY_BYPASS'|'REJECT_PROVENANCE_INCOMPLETE'|'REJECT_REPLAY_FAILURE'|'ACCEPT_GOVERNED_INVALIDATION'|'ERROR_MALFORMED_INPUT';
type Failure='NONE'|'AUTHORITY_BYPASS'|'EVIDENCE_MISSING'|'EVIDENCE_UNREGISTERED'|'EVIDENCE_INVALIDATED'|'EPISTEMIC_UNSUPPORTED'|'PROVENANCE_INCOMPLETE'|'REPLAY_DIVERGENCE'|'EXTENSION_BYPASS'|'MALFORMED_INPUT'|'CONFLICT_UNRESOLVED';
type Status='PASS'|'FAIL'|'ERROR'|'UNRESOLVED';
interface Evidence{id:string;content:string;status:'ADMISSIBLE'|'INVALIDATED';provenance:string}
interface Proposal{id:string;actor_type:'COGNITIVE'|'EXECUTION'|'AUTHORITY';claim:string;confidence:number;evidence_ids:string[];provider:string;runtime:string;requested_transition:string;human_approval?:{approved:boolean;provenance_complete:boolean}}
interface Fixture{fixture_id:string;fixture_version:string;description:string;target_invariants:string[];expected_decision:Decision;expected_failure_code:Failure;required_evidence_ids:string[];policy_version:string;authority_context_id:string;provider_variants:string[];bypass_attempts:string[];expected_replay_match:boolean;evidence:Evidence[];proposal:Proposal}
interface Manifest{manifest_version:string;canonicalization_profile:string;hash_algorithm:'sha256';fixtures:Fixture[]}
interface Record{benchmark_id:string;harness_version:string;fixture_id:string;invariant_id:string;engine_version:string;input_hash:string;evidence_snapshot_hash:string;policy_snapshot_hash:string;authority_context_hash:string;decision:Decision;canonical_transition_hash:string|null;provenance_hash:string;replay_decision_hash:string|null;replay_match:boolean|null;bypass_attempt:string|null;bypass_result:string|null;status:Status;failure_code:Failure;severity:'INFO'|'MINOR'|'MAJOR'|'BLOCKER';artifact_refs:string[]}
const ROOT=process.cwd(),MANIFEST=join(ROOT,'benchmarks/comp-m1-1/fixtures.json'),OUTPUT=join(ROOT,'verification/comp-m1-1/m1-1-execution.json');
const INVARIANTS=['INV-AUTH-01','INV-EVID-01','INV-EPIST-01','INV-CAUSAL-01','INV-PROV-01','INV-MOD-01','INV-GOV-01'];
const SEVERITY:Record<Failure,Record['severity']>={NONE:'INFO',AUTHORITY_BYPASS:'BLOCKER',EVIDENCE_MISSING:'BLOCKER',EVIDENCE_UNREGISTERED:'BLOCKER',EVIDENCE_INVALIDATED:'MAJOR',EPISTEMIC_UNSUPPORTED:'BLOCKER',PROVENANCE_INCOMPLETE:'BLOCKER',REPLAY_DIVERGENCE:'BLOCKER',EXTENSION_BYPASS:'BLOCKER',MALFORMED_INPUT:'MAJOR',CONFLICT_UNRESOLVED:'MAJOR'};
const c=(x:unknown):unknown=>Array.isArray(x)?x.map(c):x&&typeof x==='object'?Object.fromEntries(Object.entries(x as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,c(v)])):typeof x==='string'&&/^\d{4}-\d\d-\d\dT/.test(x)?new Date(x).toISOString():x;
const json=(x:unknown)=>JSON.stringify(c(x)),h=(d:string,x:unknown)=>createHash('sha256').update(`CODESSA-COMP-M1-1:${d}:v1\n${json(x)}`).digest('hex');
const validate=(f:Fixture)=>{if(!/^COMP-M1-1-FX-\d{4}$/.test(f.fixture_id)||!/^v\d+\.\d+$/.test(f.fixture_version)||f.proposal.confidence<0||f.proposal.confidence>1||!f.policy_version||!f.authority_context_id||!f.provider_variants.length||!f.target_invariants.some(x=>INVARIANTS.includes(x)))throw Error('MALFORMED_INPUT')};
class Registry{m=new Map<string,Evidence>();add(e:Evidence){this.m.set(e.id,{...e})}invalidate(id:string){const e=this.m.get(id);if(!e)throw Error('MALFORMED_INPUT');e.status='INVALIDATED'}snapshot(ids:string[]){return ids.map(id=>this.m.get(id)).filter((x):x is Evidence=>!!x)}}
class Authority{version='M1-1-AUTH-ENGINE-v0.1';decide(p:Proposal,e:Evidence[],required:string[],policy:string){const neutral={...p,provider:'<PROVIDER_NEUTRAL>',runtime:'<RUNTIME_NEUTRAL>'},input_hash=h('authority-input',{proposal:neutral,evidence:e,policy,authority:'AUTHORITY_ENGINE',engine:this.version}),r=(decision:Decision,failure:Failure,transition:string|null=null)=>({decision,failure_code:failure,transition,input_hash});if(p.actor_type!=='AUTHORITY'&&p.requested_transition==='DIRECT_CANONICAL_WRITE')return r('REJECT_AUTHORITY_BYPASS','AUTHORITY_BYPASS');for(const id of required){const x=e.find(v=>v.id===id);if(!x)return r('REJECT_NON_CANONICAL','EVIDENCE_UNREGISTERED');if(x.status!=='ADMISSIBLE')return r('REJECT_NON_CANONICAL','EVIDENCE_INVALIDATED')}if(!required.length&&p.confidence>0)return r('REJECT_NON_CANONICAL','EPISTEMIC_UNSUPPORTED');if(p.human_approval?.approved&&!p.human_approval.provenance_complete)return r('REJECT_PROVENANCE_INCOMPLETE','PROVENANCE_INCOMPLETE');if(p.requested_transition==='CONFLICTING_TOOL_UPDATE')return r('DEFER_PENDING_EVIDENCE','CONFLICT_UNRESOLVED');return r('ACCEPT_CANONICAL','NONE',p.requested_transition)}}
const run=(f:Fixture,provider:string,a:Authority):Record[]=>{const reg=new Registry();f.evidence.forEach(e=>reg.add(e));if(f.fixture_id==='COMP-M1-1-FX-0007')reg.invalidate(f.required_evidence_ids[0]);const e=reg.snapshot(f.proposal.evidence_ids),p={...f.proposal,provider},d=a.decide(p,e,f.required_evidence_ids,f.policy_version),re=a.decide(p,e,f.required_evidence_ids,f.policy_version),replay=h('decision',re),dh=h('decision',d),transition=d.transition?h('canonical-transition',{transition:d.transition,input_hash:d.input_hash}):null,receipt={proposal_id:p.id,actor_type:p.actor_type,provider:p.provider,runtime:p.runtime,evidence_ids:p.evidence_ids,evidence:h('evidence',e),decision:d.decision,decision_hash:dh},pass=d.decision===f.expected_decision&&d.failure_code===f.expected_failure_code&&(!f.expected_replay_match||replay===dh),bypass=f.bypass_attempts[0]??null;return f.target_invariants.map(invariant_id=>({benchmark_id:'CODESSA-COMP-M1-1',harness_version:'v0.1',fixture_id:f.fixture_id,invariant_id,engine_version:a.version,input_hash:d.input_hash,evidence_snapshot_hash:h('evidence-snapshot',e),policy_snapshot_hash:h('policy',f.policy_version),authority_context_hash:h('authority-context',f.authority_context_id),decision:d.decision,canonical_transition_hash:transition,provenance_hash:h('provenance',receipt),replay_decision_hash:f.expected_replay_match?replay:null,replay_match:f.expected_replay_match?replay===dh:null,bypass_attempt:bypass,bypass_result:bypass?'REJECTED':null,status:pass?'PASS':'FAIL',failure_code:d.failure_code,severity:SEVERITY[d.failure_code],artifact_refs:['verification/comp-m1-1/m1-1-execution.json']}))};
const main=()=>{const m=JSON.parse(readFileSync(MANIFEST,'utf8')) as Manifest,a=new Authority(),records:Record[]=[];for(const f of m.fixtures){try{validate(f);for(const p of f.provider_variants)records.push(...run(f,p,a))}catch(error){records.push(...f.target_invariants.map(invariant_id=>({benchmark_id:'CODESSA-COMP-M1-1',harness_version:'v0.1',fixture_id:f.fixture_id,invariant_id,engine_version:a.version,input_hash:h('malformed',f),evidence_snapshot_hash:h('evidence-snapshot',f.evidence),policy_snapshot_hash:h('policy',f.policy_version),authority_context_hash:h('authority-context',f.authority_context_id),decision:'ERROR_MALFORMED_INPUT' as Decision,canonical_transition_hash:null,provenance_hash:h('provenance',{fixture_id:f.fixture_id,decision:'ERROR_MALFORMED_INPUT'}),replay_decision_hash:null,replay_match:null,bypass_attempt:null,bypass_result:null,status:(f.expected_decision==='ERROR_MALFORMED_INPUT'?'PASS':'FAIL') as Status,failure_code:'MALFORMED_INPUT' as Failure,severity:'MAJOR' as const,artifact_refs:['verification/comp-m1-1/m1-1-execution.json']})))}}
const by=(id:string)=>records.filter(r=>r.fixture_id===id),self=Array.from({length:10},(_,i)=>{const fixture=`COMP-M1-1-FX-${String(i+1).padStart(4,'0')}`;return{id:`ST-${String(i+1).padStart(3,'0')}`,fixture,status:by(fixture).length>0&&by(fixture).every(r=>r.status==='PASS')?'PASS':'FAIL'}});const p=by('COMP-M1-1-FX-0008');self[7].status=p.length===2&&new Set(p.map(r=>r.input_hash)).size===1&&new Set(p.map(r=>r.decision)).size===1?'PASS':'FAIL';const acceptance={all_self_tests_pass:self.every(x=>x.status==='PASS'),result_schema_valid:records.every(r=>!!r.benchmark_id&&!!r.input_hash&&!!r.provenance_hash),replay_hashes_match:records.filter(r=>r.replay_match!==null).every(r=>r.replay_match===true),mutation_expected_failures:by('COMP-M1-1-FX-0007').every(r=>r.failure_code==='EVIDENCE_INVALIDATED'&&r.status==='PASS')&&by('COMP-M1-1-FX-0009').every(r=>r.failure_code==='AUTHORITY_BYPASS'&&r.status==='PASS'),governed_error_handling:by('COMP-M1-1-FX-0010').every(r=>r.decision==='ERROR_MALFORMED_INPUT'&&r.failure_code==='MALFORMED_INPUT'&&r.status==='PASS'),stable_artifact_reference:true},conformance=Object.values(acceptance).every(Boolean)?'CONFORMANT':self.some(x=>x.status==='FAIL')?'NON-CONFORMANT':'UNRESOLVED',impl=createHash('sha256').update(readFileSync(join(ROOT,'tools/competitive/verify-m1-1.ts'))).digest('hex'),fixtures=createHash('sha256').update(readFileSync(MANIFEST)).digest('hex'),out={benchmark_id:'CODESSA-COMP-M1-1',harness_version:'v0.1',execution_profile:m.canonicalization_profile,hash_algorithm:'sha256',implementation_sha256:impl,fixture_manifest_sha256:fixtures,conformance,self_tests:self,acceptance,record_count:records.length,records};mkdirSync(join(ROOT,'verification/comp-m1-1'),{recursive:true});const text=json(out)+'\n';writeFileSync(OUTPUT,text);const sha=createHash('sha256').update(text).digest('hex');writeFileSync(`${OUTPUT}.sha256`,`${sha}  m1-1-execution.json\n`);console.log(`CONFORMANCE=${conformance}\nSELF_TESTS=${self.filter(x=>x.status==='PASS').length}/10\nRECORDS=${records.length}\nSHA256=${sha}`);if(conformance!=='CONFORMANT')process.exitCode=1};main();
